export enum MaterialType {
  ALUMINUM = 'ALUMINUM',
  CARDBOARD = 'CARDBOARD',
  PLASTIC = 'PLASTIC',
  GLASS = 'GLASS',
  METAL = 'METAL',
  COOKING_OIL = 'COOKING_OIL',
  SMALL_ELECTRONICS = 'SMALL_ELECTRONICS',
  MIXED = 'MIXED',
}
